name: ci/cd

on:
  push:
    branches: [ master, release/*]
  pull_request:
    branches: [ master, release/*]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        otp_version: [19, 20, 21, 22, 23]
        # otp_version: [19]
        os: [ubuntu-16.04]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Build Library
      run: make tv-lib
    - name: Build Examples
      run: make examples

